'use client'
import './globals.css'
import localFont from 'next/font/local'
import Header from '@/components/Header/Header'
import useBlur from '@/hooks/useBlur'
import { usePathname } from 'next/navigation'
import Footer from '@/components/Footer/Footer'

const futura = localFont({ src: '../assets/fonts/futura.woff2' })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const blurValue = useBlur(20)
  const router = usePathname()

  function handleVideo () {
    //switch for scalability
    switch(router){
      case "/": 
        return "vid01.mp4"
      case "/store":
        return "vid02.mp4"
      case "/contact":
        return "vid01.mp4"
    }
  }

  return (
    <html lang="en">
      <body className={futura.className}>
        <div className="videoCont">
          <video
            className="video" 
            src={handleVideo()} 
            style={{ filter: `blur(${blurValue}px) brightness(0.9)` }}
            autoPlay muted loop
          />
        </div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
