import './globals.css'
import localFont from 'next/font/local'
import Header from '@/components/Header/Header'



const futura = localFont({ src: '../assets/fonts/futura.woff2' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={futura.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
